// Direct imports for each icon to ensure they load properly
import {
    FileText,
    File,
    Folder,
    FolderOpen,
    Type,
    Text,
    Heading,
    List,
    Quote,
    Code,
    Link,
    Image,
    Video,
    Music,
    Camera,
    Palette,
    Brush,
    MessageCircle,
    Mail,
    Phone,
    Share,
    Send,
    Home,
    Search,
    Settings,
    Menu,
    ArrowRight,
    ArrowLeft,
    DollarSign,
    TrendingUp,
    BarChart,
    Calculator,
    CreditCard,
    Clock,
    Calendar,
    Timer,
    Watch,
    Wrench,
    Hammer,
    Key,
    Lock,
    Unlock,
    Sun,
    Moon,
    Cloud,
    Leaf,
    User,
    Users,
    Heart,
    ThumbsUp,
    Star,
    Smile,
} from 'lucide-react';
  
export const ICON_MAP: Record<string, React.ComponentType<any>> = {
    FileText,
    File,
    Folder,
    FolderOpen,
    Type,
    Text,
    Heading,
    List,
    Quote,
    Code,
    Link,
    Image,
    Video,
    Music,
    Camera,
    Palette,
    Brush,
    MessageCircle,
    Mail,
    Phone,
    Share,
    Send,
    Home,
    Search,
    Settings,
    Menu,
    ArrowRight,
    ArrowLeft,
    DollarSign,
    TrendingUp,
    BarChart,
    Calculator,
    CreditCard,
    Clock,
    Calendar,
    Timer,
    Watch,
    Wrench,
    Hammer,
    Key,
    Lock,
    Unlock,
    Sun,
    Moon,
    Cloud,
    Leaf,
    User,
    Users,
    Heart,
    ThumbsUp,
    Star,
    Smile,
};
  
export const ICON_CATEGORIES = {
    'File & Document': ['FileText', 'File', 'Folder', 'FolderOpen'],
    'Writing & Text': ['Type', 'Text', 'Heading', 'List', 'Quote', 'Code', 'Link'],
    'Media & Design': ['Image', 'Video', 'Music', 'Camera', 'Palette', 'Brush'],
    'Communication': ['MessageCircle', 'Mail', 'Phone', 'Share', 'Send'],
    'Navigation & UI': ['Home', 'Search', 'Settings', 'Menu', 'ArrowRight', 'ArrowLeft'],
    'Business & Finance': ['DollarSign', 'TrendingUp', 'BarChart', 'Calculator', 'CreditCard'],
    'Time & Calendar': ['Clock', 'Calendar', 'Timer', 'Watch'],
    'Objects & Tools': ['Wrench', 'Hammer', 'Key', 'Lock', 'Unlock'],
    'Nature & Weather': ['Sun', 'Moon', 'Cloud', 'Leaf'],
    'People & Social': ['User', 'Users', 'Heart', 'ThumbsUp', 'Star', 'Smile'],
};